### ISSUE TITLE
Status bar color issue

### ISSUE THREAD

**Issue by rickdtc** [vishal2376/snaptick#1]
Hi, I found a ui bug in the app, well, what I found is that 

![1000108287 1](https://github.com/vishal2376/snaptick/assets/74096544/4604855e-7b67-4ca6-a9b2-51364581bf52)

The top icons should turn white on dark mode, here it doesn't, which causes readability issues.

All in all, the app is beutiful, it would be great if this was fixed

**Comment by vishal2376** [comment]
New update available: Snaptick v1.1
