### ISSUE TITLE
Some UI bugs

### ISSUE THREAD

**Issue by serrq** [vishal2376/snaptick#12]
Snaptick 1.0 (fdroid)
Android 13
OnePlus CPH2399

![1000106200](https://github.com/vishal2376/snaptick/assets/113377431/5655636c-1ddd-4979-a7ae-84f1a52dc6b5)

**Comment by vishal2376** [comment]
Fixed Issue
New update available: Snaptick v1.1

**Comment by vishal2376** [comment]
Can i know you device size ?

**Comment by vishal2376** [comment]
yeah i mean screen width and height

**Comment by vishal2376** [comment]
Can you send Screenshot of latest version? i want to compare the difference

**Comment by vishal2376** [comment]
Bro App home page is looking fine, where is UI error

**Comment by vishal2376** [comment]
> Updated to 1.1. The apk seems to be the same.

because of this reply.

But anyway that's scrolling issue and will be fixed soon
