### ISSUE TITLE
No way to save a new task

### ISSUE THREAD

**Issue by serrq** [vishal2376/snaptick#15]
Snaptick 1.1
Android 13
OnePlus CPH2399

Where is the "Save" button?

![1000106206](https://github.com/vishal2376/snaptick/assets/113377431/3d44a8d3-5de2-45ab-b8b6-45c421f25bdc)

**Comment by vishal2376** [comment]
![Screenshot_2024-02-19-22-28-18-005_com.vishal2376.snaptick.jpg](https://github.com/vishal2376/snaptick/assets/38159691/7acd9a4e-2788-4dff-8e95-36590abaccbb)

Your device is smaller , that's why it cropped.


I will implement vertical scroll tomorrow
