### ISSUE TITLE
Localization Support (30+ languages)

### ISSUE THREAD

**Issue by vishal2376** [vishal2376/snaptick#18]
## Add 30+ languages translations for native users

- Crowdin Project link : https://crowdin.com/project/snaptick

**Comment by ngocanhtve** [comment]
Great! I'm eagerly waiting for you to implement strings!

**Comment by Coding-Meet** [comment]
languages translations easy without any api key 
check out my repo: https://github.com/Coding-Meet/String-Translator-Desktop-App
