### ISSUE TITLE
Enhancement: material you colors

### ISSUE THREAD

**Issue by AnotherRandomGitHubAccount** [vishal2376/snaptick#19]
Would like option to use material you colors in app

**Comment by vishal2376** [comment]
https://github.com/user-attachments/assets/5e0ef6d3-3e92-4138-8a0e-d812c74a122d

**Comment by Drsheppard01** [comment]
Can you provide widget with Material You?

**Comment by vishal2376** [comment]
@Drsheppard01  I don't think it's available for `Glance Widget APIs` (used for making Widget). I will add _material you_ if it's available in the future.
