### ISSUE TITLE
Repeated tasks not shown on planner (after their first end)

### ISSUE THREAD

**Issue by serrq** [vishal2376/snaptick#20]
![1000106240](https://github.com/vishal2376/snaptick/assets/113377431/28a4964c-2efb-45fa-b095-71150141d4b9)

**Comment by vishal2376** [comment]
I found the issue : repeated tasks are loading properly, but they are already completed.

This app only show today's tasks (both completed and incompleted).

**Comment by vishal2376** [comment]
working on it
