### ISSUE TITLE
[Feature] Light theme

### ISSUE THREAD

**Issue by ngocanhtve** [vishal2376/snaptick#24]
First of all, thank you for a very nice application. It would be great if the app supported a light theme, preferably a follow system option.
Thank you!

**Comment by vishal2376** [comment]
Currently app looks bad in light theme. So i am doing experiment with different color shades that's why it still not implemented.

I want to make themes look like premium apps (it willl remain free in my app)

and Thanks for appreciation 😊

**Comment by vishal2376** [comment]
![20240225_121327.jpg](https://github.com/vishal2376/snaptick/assets/38159691/7bff5b7a-ffeb-414c-8c85-46dc2199ab39)

@ngocanhtve I don't use light theme, so i want feedback from light theme users

please let me know, if you find any issues like readability issue, color contrast, etc

**Comment by ngocanhtve** [comment]
> please let me know, if you find any issues like readability issue, color contrast, etc

It's good. Sir!

**Comment by ngocanhtve** [comment]
I think a slightly lighter color range would be more soothing to the eyes.

**Comment by vishal2376** [comment]
Demo - https://x.com/vishal2376/status/1765010912342143293?s=20
