### ISSUE TITLE
Heatmap Calender Chart 

### ISSUE THREAD

**Issue by saltsoftdrink** [vishal2376/snaptick#27]
Is it possible to add heatmap chart for habits - https://github.com/kizitonwose/Calendar

The last one in image with green dots

https://user-images.githubusercontent.com/15170090/197389318-b3925b65-aed9-4e1f-a778-ba73007cbdf7.png

**Comment by vishal2376** [comment]
@saltsoftdrink Thanks for heatmap suggestion
