### ISSUE TITLE
No alarm for recurring tasks (after their first end)

### ISSUE THREAD

**Issue by serrq** [vishal2376/snaptick#31]
Android 14
OnePlus CPH2399
1.1.2

Also the strike number advances by itself without any counter proof on the result of the completed daily tasks.

![1000106295](https://github.com/vishal2376/snaptick/assets/113377431/34057bb3-59fa-4a6e-91f9-134f19a6adc7)

**Comment by vishal2376** [comment]
Currently streak is increasing based on App opened each day regularly ( it's not a bug )

**Comment by vishal2376** [comment]
I think i have to re-implement repeat task logic from scratch with a proper design and logic flow

At initial stage I never thought of implementing repeated tasks , that's why it's still buggy with repeated tasks.

I am working on it 🫡

**Comment by vishal2376** [comment]
Fixed finally :)
