### ISSUE TITLE
Plan tasks for days other than today

### ISSUE THREAD

**Issue by pacastega** [vishal2376/snaptick#33]
I think it would be a good improvement to be able to add tasks for other days (every night plan the tasks for the following day, or on Monday morning add the tasks for the whole week, for example).

Maybe this could be achieved by allowing tasks to not have specific start/end times, so it's up to the user to work on the task when they want.

**Comment by vishal2376** [comment]
This could be possible if either the startTime/endTime is the same or if there is no startTime/endTime for the task. This will be achievable after resolving following issues.

#16 Selected Weekdays 
#23 Tasks without time

So track these issues.

I am closing this rn as it is duplicate issue 🙃
