### ISSUE TITLE
There is bug Whenever the screen is rotated timer reset itself 

### ISSUE THREAD

**Issue by Scapy47** [vishal2376/snaptick#35]

**Comment by vishal2376** [comment]
Thanks @Scapy47 for reporting bug.

I am currently prioritizing accuracy and user experience. Therefore, I have designed the app to work exclusively in portrait mode.

In the upcoming update, I will be `disabling rotation` to ensure the consistency of the UI.

However, in future updates, rotation will also be available, especially in cases like the Pomodoro screen where it is beneficial
