### ISSUE TITLE
[Feature] Integrate Native Time Picker Alongside Current Wheel Time Picker with Settings Toggle

### ISSUE THREAD

**Issue by lolayup** [vishal2376/snaptick#38]

**Comment by vishal2376** [comment]
Thanks @lolayup for your honest feedback.

Could you please suggest ways in which I can improve it?

**Comment by lolayup** [comment]
> Thanks @lolayup for your honest feedback.
> 
> Could you please suggest ways in which I can improve it?

> Thanks for the response! I propose considering these alternatives for time input:
> 
-  **Native time picker**: Utilize the Android system's native time picker for a familiar user experience.
-  **Time field**: Allow direct time input using a text field.

**Comment by vishal2376** [comment]
**Native Time Picker** would be a great choice.
Rather than removing the current time picker, I plan to integrate both options, allowing users to switch between them in the settings.

Please note that implementing this may take some time
