### ISSUE TITLE
Today view ---> Upcoming events

### ISSUE THREAD

**Issue by serrq** [vishal2376/snaptick#46]
There is a problem in Today view: it shows upcoming events only when the "day" is exactly the day.

Yesterday (sunday) I hadn't any commitments, but today (monday) I have three ones.

Why the app doesn't noticed me of three upcoming events in next 7 days?

Have I to know it at 00:00 am?

**Comment by vishal2376** [comment]
## You can see here 

![IMG_20240311_113634.jpg](https://github.com/vishal2376/snaptick/assets/38159691/59ccae6e-31ed-4c3e-b3b2-0532ea308042)
