### ISSUE TITLE
Widget Support

### ISSUE THREAD

**Issue by vishal2376** [vishal2376/snaptick#5]

**Comment by vishal2376** [comment]
@saltsoftdrink sure dude 

It will take some time, as I can't reuse my same UI code because of Glance library

**Comment by saltsoftdrink** [comment]
@vishal2376 I've a resource to make home screen widget - https://github.com/serbelga/Todometer-KMP

Just add one more thing that is reload option in widget
And, tick the items in left

**Comment by vishal2376** [comment]
Thank @saltsoftdrink for helpful resources

I will checkout and implement this after my exams

**Comment by saltsoftdrink** [comment]
> Thank @saltsoftdrink for helpful resources
> 
> I will checkout and implement this after my exams

All the best for your exams! Is your boards going on?

**Comment by vishal2376** [comment]
Thanks.  

No,  It's college exams

**Comment by tuuhin** [comment]
Is someone working on the widgets would love to work on it??
I have worked with widget in the past. Here is my work [Weather App](https://github.com/tuuhin/AndroidWeatherApp)

**Comment by vishal2376** [comment]
@tuuhin Great work.

The widget UI is done but i am facing some issues regarding updating the widget whenever there is change in the Database (like user added new task)

I am happy if you could help in this issue 

You can checkout branch `feat/widget` for widget code. Don't make any extra branch . Do it in `feat/widget` branch

**Comment by tuuhin** [comment]
I was looking over your code, you have directly used room database for the data to show in widget which doesn't seems like a good approach.
 As per my visuals you want to just use the widget as a presenter i.e., it will only show some tasks, seems like tasks that are incomplete.
 What I insist to use a secondary glance definition which will periodically update along with update on any change to the database.
 Can you describe what the widget is meant to do , ie, what information it will show , whether its responsive

**Comment by vishal2376** [comment]
@tuuhin For now, I want only these things

1. Show today's incompleted tasks
2. User can mark task as completed(✅)
3. Update widget
        - Whenever there is change in today's tasks
        - Everyday at 12:00AM midnight (sync with next day tasks)



P.S. I don't know how to use glance with hilt DI, Also i never made widget in past project that's why i am still learning phase.

**Comment by tuuhin** [comment]
If I show today's incomplete task , now user click on such a task , what should the widget do mark as check or just remove it from other incomplete ones
I think just to show incomplete tasks will be a better idea, as a widget is a small space in a screen now if I too show completed tasks it will take more space 
Thoughts ?

**Comment by vishal2376** [comment]
@tuuhin Showing only incomplete tasks will be good choice.

When user click checkbox then , mark it as completed and then remove it from the complete (lazy column will automatically handle)


Here is the reference video
https://twitter.com/vishal2376/status/1768274013220938148?t=P55AKQLEfcADeCOHSKLbQg&s=19

**Comment by vishal2376** [comment]
@tuuhin But If you still want to add Completed tasks list then you can do something like this


![IMG_20240329_234635.jpg](https://github.com/vishal2376/snaptick/assets/38159691/c7ddcad2-ff3c-41a2-8e35-10c1f0ceec95)

**Comment by tuuhin** [comment]
Yup can make it though but widget should be simple this simple complicated enough.
For the mean time let go with only incomplete tasks , if require you can change the design

**Comment by vishal2376** [comment]
@tuuhin  Can i have your contact/social handle to make development faster

**Comment by tuuhin** [comment]
I have followed you on twitter you can text me over there

**Comment by vishal2376** [comment]
Thanks @tuuhin for solving widget's major problems
