### ISSUE TITLE
"This week" doesn't show not-repeated events

### ISSUE THREAD

**Issue by serrq** [vishal2376/snaptick#54]
Today I discovered that the app only shows repeated tasks.

**Comment by vishal2376** [comment]
There is a new **Date feature** added in Snaptick v2.1, which breaks the logic of "This Week". 

I already planned to remove the "This Week" screen and implement it on the home screen with new SQL logic.
So user can directly switch between "Today Tasks" and "This Week Tasks" using the drop-down menu.
