### ISSUE TITLE
Cannot updating a past event

### ISSUE THREAD

**Issue by serrq** [vishal2376/snaptick#57]
Thus I cannot disabling the repeat option.

![1000108435](https://github.com/vishal2376/snaptick/assets/113377431/7f6ca892-2e4b-4d2f-ae78-beb62fe70f57)

**Comment by vishal2376** [comment]
How do you access edit task screen of past date ??

**Comment by vishal2376** [comment]
![image](https://github.com/vishal2376/snaptick/assets/38159691/83d4a06b-543a-4d10-bb92-57e84d42db00)
