### ISSUE TITLE
Fix monochrome app icon 

### ISSUE THREAD

**Issue by saltsoftdrink** [vishal2376/snaptick#60]

**Comment by vishal2376** [comment]
Can you describe the problem or provide some screenshots??

**Comment by saltsoftdrink** [comment]
> Can you describe the problem or provide some screenshots??

You can see all other icons and the snaptick one it really doesn't look good - https://ibb.co/hLsXNcX

**Comment by saltsoftdrink** [comment]
@vishal2376

**Comment by vishal2376** [comment]
@saltsoftdrink I had been working for 100 days straight. Now, I need some rest. I am taking a break from this project and will solve it later

Sorry for the inconvenience 🙏
