### ISSUE TITLE
Is it possible to integrate this with google services?

### ISSUE THREAD

**Issue by superbats** [vishal2376/snaptick#61]
Hi,

Is it possible to integrate this with google services like calendar, tasks, keep?

Would love if their services could have something like this to better plan my days.

**Comment by vishal2376** [comment]
@superbats Not now but definitely in future.

I am planning to add google drive, google Calendar, and many more online integrations in future.

All advance + online services will be available in `SnapTick Pro` App.

>  ⚠️ Note: Both `Snaptick` and `SnapTick Pro` will be different flavour. This Repository will remain free, open-source and privacy-friendly and will not merged with `SnapTick Pro` code.
