### ISSUE TITLE
Fix status bar appearing black in dark theme

### ISSUE THREAD

**Issue by privacyfreak84** [vishal2376/snaptick#68]
While using the dark theme, the phone's status bar appears black, making the information on it illegible. Making it white in dark and amoled (it is completely invisible on amoled mode) themes would fix this issue

Link to image that describes how it currently looks: https://imgur.com/a/byq7gpv

**Comment by vishal2376** [comment]
@privacyfreak84 It's working fine on my device.

Can you give me following details?
- Device Name
- Android Version

**Comment by privacyfreak84** [comment]
Device: Samsung Galaxy a30s
Android Version: 11
