### ISSUE TITLE
Clock Input feature

### ISSUE THREAD

**Issue by DavidusRidero** [vishal2376/snaptick#85]
Allow the clock dial to be circular i.e. show 00 after 59.

**Comment by vishal2376** [comment]
@DavidusRidero I am currently using the [Wheel TimePicker](https://github.com/commandiron/WheelPickerCompose) library, which does not yet support the [loop scrolling](https://github.com/commandiron/WheelPickerCompose/issues/23) feature. Unfortunately, there isn’t much I can do about it at the moment.

Migrating to another library could be time-consuming and might potentially break existing functionality. Therefore, I won’t be making any changes for now.
